"""update the user_id bank_transactions table

Revision ID: 56d833848461
Revises: ceb24171965d
Create Date: 2025-07-27 08:16:15.164455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d833848461'
down_revision: Union[str, Sequence[str], None] = 'ceb24171965d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_bank_transactions_user_id_users'), 'bank_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bank_transactions_user_id_users'), 'bank_transactions', type_='foreignkey')
    op.drop_column('bank_transactions', 'user_id')
    # ### end Alembic commands ###
