"""update the transaction type as string

Revision ID: a33540488e08
Revises: 56d833848461
Create Date: 2025-07-27 09:15:40.589281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33540488e08'
down_revision: Union[str, Sequence[str], None] = '56d833848461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('category_type', sa.String(length=20), nullable=True))
    op.alter_column('bank_transactions', 'transaction_type',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transactions', 'transaction_type',
               existing_type=sa.String(length=100),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_column('bank_transactions', 'category_type')
    # ### end Alembic commands ###
