// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7qb8KtXMtb6xhKWf4sLkum-D-KC5brM',
    appId: '1:807626793053:web:7ef478d30050cf79bdadb4',
    messagingSenderId: '807626793053',
    projectId: 'finhabit-agentic-6c961',
    authDomain: 'finhabit-agentic-6c961.firebaseapp.com',
    storageBucket: 'finhabit-agentic-6c961.firebasestorage.app',
    measurementId: 'G-36H7WVH5NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22l-Va3yqKlRZ4QPtW-wAfqfMr7pBYfo',
    appId: '1:807626793053:android:1ef6c8e73f4b4006bdadb4',
    messagingSenderId: '807626793053',
    projectId: 'finhabit-agentic-6c961',
    storageBucket: 'finhabit-agentic-6c961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtidDNyu9u2-YYB8cm2pRZPRJDPtnOrgw',
    appId: '1:807626793053:ios:77781cecd86fb773bdadb4',
    messagingSenderId: '807626793053',
    projectId: 'finhabit-agentic-6c961',
    storageBucket: 'finhabit-agentic-6c961.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtidDNyu9u2-YYB8cm2pRZPRJDPtnOrgw',
    appId: '1:807626793053:ios:77781cecd86fb773bdadb4',
    messagingSenderId: '807626793053',
    projectId: 'finhabit-agentic-6c961',
    storageBucket: 'finhabit-agentic-6c961.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd7qb8KtXMtb6xhKWf4sLkum-D-KC5brM',
    appId: '1:807626793053:web:ec5e1d0be435096ebdadb4',
    messagingSenderId: '807626793053',
    projectId: 'finhabit-agentic-6c961',
    authDomain: 'finhabit-agentic-6c961.firebaseapp.com',
    storageBucket: 'finhabit-agentic-6c961.firebasestorage.app',
    measurementId: 'G-WKZMQ85K2M',
  );
}
